-- INSERT INTO hospitals (name, address) VALUES
--                                           ('Bishkek Hospital', 'Чүй проспекти 123'),
--                                           ('MedCenter Clinic', 'Ибраимов көчөсү 45'),
--                                           ('City Hospital №1', 'Токтогул көчөсү 89');